openapi: 3.0.0
info:
  title: GoLearning
  version: 1.0.0
servers:
  - url: https://130.162.195.228/mhs714220021/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: UserRegistration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rezz
                password: admin12345
                email: aaaa@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: LoginUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rezz
                password: admin12345
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /courses:
    get:
      tags:
        - default
      summary: GetCourse
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostCourse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_name: Pemograman 3
                teacher: Budi
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /courses/{courseId}:
    put:
      tags:
        - default
      summary: PutCourse
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_name: Pemograman 3
                teacher: Yanto
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteCourse
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /students:
    get:
      tags:
        - default
      summary: GetStudent
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostStudent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_id: 2
                name: Reza
                class: 2A
                address: Bandung
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /students/{studentId}:
    put:
      tags:
        - default
      summary: PutStudent
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_id: 2
                name: Fatir
                class: 2A
                address: Batu
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteStudent
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            example: 2
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
